# Describes a simple example flow that generates random numbers and then copies and links across 2 additional datasets

flow:
  source: input # uncomment to use the example generator
  # source: 'input/index' # uncomment to loop over an existing dataset
  stages: [example_stage0, example_stage1, example_stage2, print]
  drop: ['example_stage2/example']

resources:
  - classname: ExampleResource
    path: examples.modules.examples  
    params:
      path: 'meta'
      data:
        val0: 0
        val1: 1
        val2: 2

input:
  classname: ExampleGenerator
  path: examples.modules.examples  
  dset_name: 'input/index'
  params:
    chunk_size: 1024

example_stage0:
  classname: ExampleStage
  path: examples.modules.examples  
  params:
    output_dset: 'stage0/example'

example_stage1:
  classname: ExampleStage
  path: examples.modules.examples
  requires:
      # load simple input/index -> example_stage0/example references
      - 'stage0/example'

      # load indices as well (@example_stage0/example_idcs)
      - name: 'stage0/example_idcs'
        path: 'stage0/example'
        index_only: True

      # load input -> example_stage0 -> input references
      - name: 'input/index_once_referred'
        path: ['stage0/example', 'input/index']

  params:
    output_dset: 'stage1/example'

example_stage2:
  classname: ExampleStage
  path: examples.modules.examples  
  params:
    output_dset: 'example_stage2/example' # remove this dataset from output file

print: # print the contents of the cache if in verbose mode
  classname: H5FlowTestStage
  path: h5flow.modules
